# Use single default monitor (see all monitors with: hyprctl monitors)
monitor=,preferred,auto,1.2

general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out =  2
    border_size = 2
}
