# Use single default monitor (see all monitors with: hyprctl monitors)
monitor=,preferred,auto,1.1

general {
    gaps_in = 0.5
    gaps_out = 0
    border_size = 2
    layout = dwindle
}


dwindle {
    pseudotile = true
    preserve_split = false
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 2

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.1

    # window opacity
    active_opacity = 1.1
    inactive_opacity = 1.1
}

animations {
    # enabled = no
}

# disable touchscreen if on laptop. 
# command to find device ID: hyprctl devices
device {
    name = gtch7503:00-2a94:d04d
    enabled = false
}
